/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/FdMH7lYrjiH
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Caudex } from 'next/font/google'
import { Fraunces } from 'next/font/google'

caudex({
  subsets: ['latin'],
  display: 'swap',
})

fraunces({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function Component1() {
  return (
    (<div className="flex flex-col min-h-[100dvh]">
      <header className="bg-primary text-primary-foreground py-4 px-6">
        <div className="container mx-auto flex items-center justify-between">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <BookIcon className="h-6 w-6" />
            <span className="text-xl font-bold">Éditions Acme</span>
          </Link>
          <nav className="hidden md:flex items-center gap-6">
            <Link
              href="#"
              className="text-sm font-medium hover:underline underline-offset-4"
              prefetch={false}>
              Accueil
            </Link>
            <Link
              href="#"
              className="text-sm font-medium hover:underline underline-offset-4"
              prefetch={false}>
              Catalogue
            </Link>
            <Link
              href="#"
              className="text-sm font-medium hover:underline underline-offset-4"
              prefetch={false}>
              Contact
            </Link>
          </nav>
          <Button variant="outline" size="sm" className="md:hidden">
            <MenuIcon className="h-5 w-5" />
            <span className="sr-only">Toggle navigation</span>
          </Button>
        </div>
      </header>
      <main className="flex-1">
        <section className="bg-muted py-12 md:py-24">
          <div className="container mx-auto px-4 md:px-6">
            <div className="grid md:grid-cols-2 gap-8 items-center">
              <div>
                <h1 className="text-4xl font-bold tracking-tight">Bienvenue chez Éditions Acme</h1>
                <p className="mt-4 text-muted-foreground">
                  Depuis plus de 20 ans, nous publions des ouvrages de fiction et de non-fiction qui inspirent, éduquent
                  et divertissent nos lecteurs. Découvrez notre catalogue de livres passionnants.
                </p>
                <div className="mt-6">
                  <Link
                    href="#"
                    className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                    prefetch={false}>
                    Voir le catalogue
                  </Link>
                </div>
              </div>
              <img
                src="/placeholder.svg"
                width="550"
                height="550"
                alt="Éditions Acme"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover" />
            </div>
          </div>
        </section>
        <section className="py-12 md:py-24">
          <div className="container mx-auto px-4 md:px-6">
            <div className="flex flex-col items-center justify-center text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tight">Nos dernières publications</h2>
                <p className="max-w-[700px] text-muted-foreground">
                  Découvrez nos derniers titres, des ouvrages qui sauront vous captiver et vous faire réfléchir.
                </p>
              </div>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 mt-8">
              <Card>
                <CardHeader>
                  <CardTitle>Le Voyage de Chihiro</CardTitle>
                  <CardDescription>Hayao Miyazaki</CardDescription>
                </CardHeader>
                <CardContent>
                  <p>
                    Une jeune fille de 10 ans, Chihiro, se retrouve projetée dans un monde fantastique peuplé de dieux
                    et de créatures mystérieuses.
                  </p>
                </CardContent>
                <CardFooter>
                  <Link
                    href="#"
                    className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                    prefetch={false}>
                    En savoir plus
                  </Link>
                </CardFooter>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>L'Étranger</CardTitle>
                  <CardDescription>Albert Camus</CardDescription>
                </CardHeader>
                <CardContent>
                  <p>
                    L'histoire d'un homme qui, face à l'absurde de l'existence, se retrouve étranger à lui-même et au
                    monde qui l'entoure.
                  </p>
                </CardContent>
                <CardFooter>
                  <Link
                    href="#"
                    className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                    prefetch={false}>
                    En savoir plus
                  </Link>
                </CardFooter>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>La Ferme des animaux</CardTitle>
                  <CardDescription>George Orwell</CardDescription>
                </CardHeader>
                <CardContent>
                  <p>
                    Une fable politique qui dénonce les dérives totalitaires d'un régime communiste à travers l'histoire
                    d'une ferme dirigée par des animaux.
                  </p>
                </CardContent>
                <CardFooter>
                  <Link
                    href="#"
                    className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                    prefetch={false}>
                    En savoir plus
                  </Link>
                </CardFooter>
              </Card>
            </div>
          </div>
        </section>
        <section className="bg-muted py-12 md:py-24">
          <div className="container mx-auto px-4 md:px-6">
            <div className="flex flex-col items-center justify-center text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tight">Notre catalogue</h2>
                <p className="max-w-[700px] text-muted-foreground">
                  Explorez notre riche catalogue de livres, des classiques aux dernières parutions.
                </p>
              </div>
              <div className="mt-8 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                <Card>
                  <CardHeader>
                    <CardTitle>Littérature</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p>Découvrez nos meilleurs romans, nouvelles et essais littéraires.</p>
                  </CardContent>
                  <CardFooter>
                    <Link
                      href="#"
                      className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                      prefetch={false}>
                      Voir la section
                    </Link>
                  </CardFooter>
                </Card>
                <Card>
                  <CardHeader>
                    <CardTitle>Jeunesse</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p>Explorez notre sélection de livres pour enfants et adolescents.</p>
                  </CardContent>
                  <CardFooter>
                    <Link
                      href="#"
                      className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                      prefetch={false}>
                      Voir la section
                    </Link>
                  </CardFooter>
                </Card>
                <Card>
                  <CardHeader>
                    <CardTitle>Essais</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p>Plongez dans nos ouvrages de réflexion et de connaissances.</p>
                  </CardContent>
                  <CardFooter>
                    <Link
                      href="#"
                      className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                      prefetch={false}>
                      Voir la section
                    </Link>
                  </CardFooter>
                </Card>
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-24">
          <div className="container mx-auto px-4 md:px-6">
            <div className="flex flex-col items-center justify-center text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tight">Contactez-nous</h2>
                <p className="max-w-[700px] text-muted-foreground">
                  Vous avez une question, une suggestion ou vous souhaitez soumettre un manuscrit ? N'hésitez pas à nous
                  contacter.
                </p>
              </div>
              <form className="mt-8 w-full max-w-md space-y-4">
                <Input type="text" placeholder="Nom" className="w-full" required />
                <Input type="email" placeholder="Email" className="w-full" required />
                <Textarea placeholder="Message" rows={4} className="w-full" required />
                <Button type="submit" className="w-full">
                  Envoyer
                </Button>
              </form>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-primary text-primary-foreground py-6">
        <div
          className="container mx-auto px-4 md:px-6 flex flex-col md:flex-row items-center justify-between">
          <p className="text-sm">&copy; 2024 Éditions Acme. Tous droits réservés.</p>
          <nav className="flex items-center gap-4 mt-4 md:mt-0">
            <Link
              href="#"
              className="text-sm hover:underline underline-offset-4"
              prefetch={false}>
              Mentions légales
            </Link>
            <Link
              href="#"
              className="text-sm hover:underline underline-offset-4"
              prefetch={false}>
              Politique de confidentialité
            </Link>
          </nav>
        </div>
      </footer>
    </div>)
  );
}

function BookIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>)
  );
}


function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}
