/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Ju9IAKbdlcX
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Yeseva_One } from 'next/font/google'
import { DM_Serif_Display } from 'next/font/google'

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

dm_serif_display({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function Component3() {
  return (
    (<div className="flex flex-col min-h-[100dvh]">
      <header className="bg-primary text-primary-foreground py-4 px-6">
        <div className="container mx-auto flex items-center justify-between">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <BookIcon className="h-6 w-6" />
            <span className="text-xl font-bold">Éditions Acme</span>
          </Link>
          <nav className="hidden md:flex items-center gap-4">
            <Link href="#" className="hover:underline" prefetch={false}>
              Accueil
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Nos Livres
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              À Propos
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Contact
            </Link>
          </nav>
          <Button variant="outline" className="md:hidden">
            <MenuIcon className="h-6 w-6" />
          </Button>
        </div>
      </header>
      <main className="flex-1">
        <section className="bg-muted py-12 md:py-24">
          <div className="container mx-auto px-4 md:px-6">
            <div className="grid md:grid-cols-2 gap-8 items-center">
              <div>
                <h1 className="text-4xl font-bold mb-4">Bienvenue chez Éditions Acme</h1>
                <p className="text-muted-foreground mb-6">
                  Depuis plus de 20 ans, nous publions des ouvrages de qualité dans des domaines variés. Découvrez notre
                  catalogue et rejoignez-nous !
                </p>
                <Link
                  href="#"
                  className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                  prefetch={false}>
                  Nos Livres
                </Link>
              </div>
              <img
                src="/placeholder.svg"
                width={600}
                height={400}
                alt="Éditions Acme"
                className="rounded-lg"
                style={{ aspectRatio: "600/400", objectFit: "cover" }} />
            </div>
          </div>
        </section>
        <section className="py-12 md:py-24">
          <div className="container mx-auto px-4 md:px-6">
            <h2 className="text-3xl font-bold mb-8">Nos Dernières Parutions</h2>
            <div
              className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
              <Card>
                <img
                  src="/placeholder.svg"
                  width={300}
                  height={450}
                  alt="Livre 1"
                  className="rounded-t-lg"
                  style={{ aspectRatio: "300/450", objectFit: "cover" }} />
                <CardContent>
                  <h3 className="text-lg font-bold mb-2">Titre du Livre 1</h3>
                  <p className="text-muted-foreground">Auteur du Livre 1</p>
                </CardContent>
              </Card>
              <Card>
                <img
                  src="/placeholder.svg"
                  width={300}
                  height={450}
                  alt="Livre 2"
                  className="rounded-t-lg"
                  style={{ aspectRatio: "300/450", objectFit: "cover" }} />
                <CardContent>
                  <h3 className="text-lg font-bold mb-2">Titre du Livre 2</h3>
                  <p className="text-muted-foreground">Auteur du Livre 2</p>
                </CardContent>
              </Card>
              <Card>
                <img
                  src="/placeholder.svg"
                  width={300}
                  height={450}
                  alt="Livre 3"
                  className="rounded-t-lg"
                  style={{ aspectRatio: "300/450", objectFit: "cover" }} />
                <CardContent>
                  <h3 className="text-lg font-bold mb-2">Titre du Livre 3</h3>
                  <p className="text-muted-foreground">Auteur du Livre 3</p>
                </CardContent>
              </Card>
              <Card>
                <img
                  src="/placeholder.svg"
                  width={300}
                  height={450}
                  alt="Livre 4"
                  className="rounded-t-lg"
                  style={{ aspectRatio: "300/450", objectFit: "cover" }} />
                <CardContent>
                  <h3 className="text-lg font-bold mb-2">Titre du Livre 4</h3>
                  <p className="text-muted-foreground">Auteur du Livre 4</p>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="bg-muted py-12 md:py-24">
          <div className="container mx-auto px-4 md:px-6">
            <div className="grid md:grid-cols-2 gap-8 items-center">
              <img
                src="/placeholder.svg"
                width={600}
                height={400}
                alt="À Propos"
                className="rounded-lg"
                style={{ aspectRatio: "600/400", objectFit: "cover" }} />
              <div>
                <h2 className="text-3xl font-bold mb-4">À Propos de Nous</h2>
                <p className="text-muted-foreground mb-6">
                  Éditions Acme est une maison d'édition indépendante fondée en 2000. Nous publions des ouvrages de
                  fiction et de non-fiction dans des domaines variés, avec pour objectif de découvrir et de promouvoir
                  de nouveaux talents.
                </p>
                <p className="text-muted-foreground mb-6">
                  Notre équipe est composée de passionnés du livre, soucieux de la qualité de nos publications et de
                  l\'accompagnement de nos auteurs. Rejoignez-nous pour faire partie de cette aventure !
                </p>
                <Link
                  href="#"
                  className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                  prefetch={false}>
                  En Savoir Plus
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-24">
          <div className="container mx-auto px-4 md:px-6">
            <h2 className="text-3xl font-bold mb-8">Contactez-Nous</h2>
            <div className="grid md:grid-cols-2 gap-8">
              <div>
                <p className="text-muted-foreground mb-4">
                  Vous avez un projet d'écriture ? Vous souhaitez nous soumettre un manuscrit ? N'hésitez pas à nous
                  contacter, nous serons ravis d'étudier votre dossier.
                </p>
                <form className="space-y-4">
                  <div className="grid gap-2">
                    <Label htmlFor="name">Nom</Label>
                    <Input id="name" placeholder="Votre nom" />
                  </div>
                  <div className="grid gap-2">
                    <Label htmlFor="email">Email</Label>
                    <Input id="email" type="email" placeholder="Votre email" />
                  </div>
                  <div className="grid gap-2">
                    <Label htmlFor="message">Message</Label>
                    <Textarea id="message" rows={5} placeholder="Votre message" />
                  </div>
                  <Button type="submit">Envoyer</Button>
                </form>
              </div>
              <div>
                <h3 className="text-2xl font-bold mb-4">Nos Coordonnées</h3>
                <div className="space-y-2">
                  <div className="flex items-center gap-2">
                    <MapPinIcon className="h-5 w-5 text-muted-foreground" />
                    <p>123 Rue des Éditions, 75000 Paris</p>
                  </div>
                  <div className="flex items-center gap-2">
                    <PhoneIcon className="h-5 w-5 text-muted-foreground" />
                    <p>01 23 45 67 89</p>
                  </div>
                  <div className="flex items-center gap-2">
                    <MailIcon className="h-5 w-5 text-muted-foreground" />
                    <p>contact@editions-acme.com</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-muted text-muted-foreground py-6">
        <div
          className="container mx-auto px-4 md:px-6 flex flex-col md:flex-row items-center justify-between">
          <p>&copy; 2024 Éditions Acme. Tous droits réservés.</p>
          <nav className="flex items-center gap-4 mt-4 md:mt-0">
            <Link href="#" className="hover:underline" prefetch={false}>
              Accueil
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Nos Livres
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              À Propos
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Contact
            </Link>
          </nav>
        </div>
      </footer>
    </div>)
  );
}

function BookIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>)
  );
}


function MailIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>)
  );
}


function MapPinIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z" />
      <circle cx="12" cy="10" r="3" />
    </svg>)
  );
}


function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function PhoneIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>)
  );
}
